name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: print greeting
        run: | 
             echo "hello world"
             echo "hello to chetan from anusha!!!!"
      - name: print Done
        run: echo "hello goodbye!!"
        
