name: "Test Project"
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
  deploy:
    needs: test ### to run this job sequentially, after executing test job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying!!!!!"

